<Project>
  <PropertyGroup>
    <Version Condition="'$(Version)' == ''">0.23.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    
    <!-- Shared properties for all projects -->
    <Authors>Uninstaller Team</Authors>
    <Company>Uninstaller</Company>
    <Product>Uninstaller</Product>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>
</Project>
