// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uninstaller.Infrastructure.Persistence;

#nullable disable

namespace Uninstaller.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828185859_Phase5F_TransactionJournal")]
    partial class Phase5F_TransactionJournal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Uninstaller.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EstimatedSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InstallDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallLocation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWindowsInstaller")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuietUninstallCommand")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryKeyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrySource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UninstallCommand")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RegistryKeyName");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.Backup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtifactType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedRegistryHive")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedRegistryKeyPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedShortcutTarget")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.CleanupPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UninstallSessionId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UninstallSessionId");

                    b.ToTable("CleanupPlans");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.CleanupPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AppliedRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtifactType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CleanupPlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CleanupPlanId");

                    b.ToTable("CleanupPlanItems");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BackupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReversible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("SessionId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.TransactionJournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "SequenceNumber");

                    b.ToTable("TransactionJournalEntries");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.UninstallSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strategy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationResult")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("UninstallSessions");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.Artifact", b =>
                {
                    b.HasOne("Uninstaller.Domain.Entities.UninstallSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.Backup", b =>
                {
                    b.HasOne("Uninstaller.Domain.Entities.UninstallSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.CleanupPlan", b =>
                {
                    b.HasOne("Uninstaller.Domain.Entities.UninstallSession", null)
                        .WithMany()
                        .HasForeignKey("UninstallSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Uninstaller.Domain.Entities.CleanupPlanSummary", "Summary", b1 =>
                        {
                            b1.Property<Guid>("CleanupPlanId");

                            b1.Property<int>("BlockedItems");

                            b1.Property<long?>("EstimatedRecoverableSize");

                            b1.Property<int>("ProtectedItems");

                            b1.Property<int>("RecommendedItems");

                            b1.Property<int>("SharedItems");

                            b1.Property<int>("TotalArtifacts");

                            b1.Property<int>("UnknownItems");

                            b1.Property<int>("UserDataItems");

                            b1.HasKey("CleanupPlanId");

                            b1.ToTable("CleanupPlans");

                            b1
                                .ToJson("Summary")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("CleanupPlanId");
                        });

                    b.Navigation("Summary")
                        .IsRequired();
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.CleanupPlanItem", b =>
                {
                    b.HasOne("Uninstaller.Domain.Entities.CleanupPlan", null)
                        .WithMany("Items")
                        .HasForeignKey("CleanupPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Uninstaller.Domain.Entities.Evidence", "Evidence", b1 =>
                        {
                            b1.Property<Guid>("CleanupPlanItemId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.Property<string>("Source")
                                .IsRequired();

                            b1.Property<int>("Type");

                            b1.HasKey("CleanupPlanItemId", "__synthesizedOrdinal");

                            b1.ToTable("CleanupPlanItems");

                            b1
                                .ToJson("Evidence")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("CleanupPlanItemId");
                        });

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.LogEntry", b =>
                {
                    b.HasOne("Uninstaller.Domain.Entities.UninstallSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.Operation", b =>
                {
                    b.HasOne("Uninstaller.Domain.Entities.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uninstaller.Domain.Entities.UninstallSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.UninstallSession", b =>
                {
                    b.HasOne("Uninstaller.Domain.Entities.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Uninstaller.Domain.Entities.CleanupPlan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
